from SCRIPTS.DATA_CLEANING import COMBINE_INTERFACE, LOAD_RAW_DATA, CLEAN_EXPENSE_DATA, SAVE_PROCESSED_DATA, DETECT_OUTLIERS_IQR_PER_CATEGORY

def main():
    RAW_FILE_PATH = 'DATA/RAW/'
    COMBINED_FILE = 'DATA/RAW/CASH_FLOW_COMBINED.csv'
    FULL_DATASET_CLEANED_PATH = 'DATA/PROCESSED/CASH_FLOW_CLEANED.csv'
    EXPENSES_CLEANED_PATH = 'DATA/PROCESSED/EXPENSES_CLEANED.csv'
    INCOME_CLEANED_PATH = 'DATA/PROCESSED/INCOME_CLEANED.csv'

    # Combine multiple interfaces
    COMBINE_INTERFACE(RAW_FILE_PATH, COMBINED_FILE)

    # Load data
    CASH_FLOW_DF = LOAD_RAW_DATA(COMBINED_FILE)

    # Clean data
    CLEANED_CASH_FLOW_DF = CLEAN_EXPENSE_DATA(CASH_FLOW_DF)

    # Flag Outliers
    CLEANED_CASH_FLOW_DF = DETECT_OUTLIERS_IQR_PER_CATEGORY(CLEANED_CASH_FLOW_DF, "Category", "Amount")

    # Save cleaned data
    SAVE_PROCESSED_DATA(CLEANED_CASH_FLOW_DF, FULL_DATASET_CLEANED_PATH, EXPENSES_CLEANED_PATH, INCOME_CLEANED_PATH)

    print("Cash Flow data cleaned and saved successfully!")

if __name__ == '__main__':
    main()
